Update secret-checker.yml

diff --git a/.github/workflows/secret-checker.yml b/.github/workflows/secret-checker.yml
--- a/.github/workflows/secret-checker.yml
+++ b/.github/workflows/secret-checker.yml
@@ -22,23 +22,25 @@ jobs:
     - name: Validate yaml for changed files
       id: validate-yaml
       run: |
+        secretsPathRegex="^\/secrets.*"
         for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
-          if [[ "$file" =~ "^\/secrets.*"]]; then
-            echo "Evaluating $file..."
-            yq eval $file || (echo "$file yaml format failed! Check your format."  && exit 1)
-            echo "$file check exited with $? status"
-          fi
+        if [[ "$file" =~ $secretsPathRegex ]]; then
+          echo "Evaluating $file..."
+          yq eval $file || (echo "$file yaml format failed! Check your format."  && exit 1)
+          echo "$file check exited with $? status"
+        fi
         done
 
     - name: Check line format
       if: steps.validate-yaml.outcome == 'success' 
       run: |
-        regexExp="^[A-Z0-9_]+: ENC\[PKCS7,MII[A-Za-z0-9+\/=]+]"
+        secretsPathRegex="^\/secrets.*"
+        secretStringRegex="^[A-Z0-9_]+: ENC\[PKCS7,MII[A-Za-z0-9+\/=]+]"
         for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
-          if [[ "$file" =~ "^\/secrets.*"]]; then
+          if [[ "$file" =~ $secretsPathRegex]]; then
             while IFS= read -r line || [ -n "$line" ]; do
               echo "validating secret: $line"
-              [[ "$line" =~ $regexExp ]] && echo "this secret is valid" || (echo "this secret is invalid." && exit 1)
+              [[ "$line" =~ $secretStringRegex ]] && echo "this secret is valid" || (echo "this secret is invalid." && exit 1)
             done <$file
           fi
         done
