a

diff --git a/.github/workflows/secret-checker.yml b/.github/workflows/secret-checker.yml
--- a/.github/workflows/secret-checker.yml
+++ b/.github/workflows/secret-checker.yml
@@ -23,9 +23,12 @@ jobs:
       id: validate-yaml
       run: |
         for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
-          echo "Evaluating $file..."
-          yq eval $file || (echo "$file yaml format failed! Check your format."  && exit 1)
-          echo "$file check exited with $? status"
+          if [[ "$file" =~ "^\/secrets.*"]];
+          then
+            echo "Evaluating $file..."
+            yq eval $file || (echo "$file yaml format failed! Check your format."  && exit 1)
+            echo "$file check exited with $? status"
+          fi
         done
 
     - name: Check line format
@@ -33,10 +36,13 @@ jobs:
       run: |
         regexExp="^[A-Z0-9_]+: ENC\[PKCS7,MII[A-Za-z0-9+\/=]+]"
         for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
-          while IFS= read -r line || [ -n "$line" ]; do
-            echo "validating secret: $line"
-            [[ "$line" =~ $regexExp ]] && echo "this secret is valid" || (echo "this secret is invalid." && exit 1)
-          done <$file
+          if [[ "$file" =~ "^\/secrets.*"]];
+          then
+            while IFS= read -r line || [ -n "$line" ]; do
+              echo "validating secret: $line"
+              [[ "$line" =~ $regexExp ]] && echo "this secret is valid" || (echo "this secret is invalid." && exit 1)
+            done <$file
+          fi
         done
   auto_approve_secret_pr:
     if: ${{ (github.event.review.state == 'approved')  && (contains(github.event.pull_request.labels.*.name, 'secrets')) }}
